### PR TITLE
Add password support

### PR DESCRIPTION
**Pull request by claytono**
We want this for the ability to have passworded sudo.  If a password
isn't provided then it defaults to a locked password

### CODE REVIEW

**Comment by Cougar** [comment]
+1

**Comment by galaux** [comment]
Nice and clean. Works OK. Would love to see this patch accepted. :+1:

**Comment by claytono** [comment]
We're actually not even using this for passworded sudo anymore, but we still need the ability to have user accounts you can login as on the console, if something goes horribly wrong.

**Comment by galaux** [comment]
Thank you!

**Pull request merged**
